## TECHIN 513 HW1 – Modifying Signals

Jackie(Jie) Ji

## Summary

In this lab, you will work through a series of exercises to introduce you to working with audio signals and explore the impact of different amplitude and time operations on signals.  This is a two-week hw.  You should plan on completing the first 2 assignments in the first week.

## HW 1 turn in checklist

•	your Jupyter or Colab notbooks (uploaded as .pdf with your outputs).

Note: You can work together but you need to submit your own work. do not copy paste from each other


## Assignment 1 -- Working with sound files

In [17]:
pip install scipy numpy

  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/0d/4a/b2b2cae0c5dfd46361245a67102886ed7188805bdf7044e36fe838bbcf26/scipy-1.12.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 332.7 kB/s eta 0:00:00a 0:00:01
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/6d/66/5ea5b8ef7cb3f72ecd6c905abc2331f999bf7e9de247f9db8cc9642f0eda/numpy-1.26.3-cp312-cp312-macosx_10_9_x86_64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 1.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.9/38.9 MB 18.2 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 19.2 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [23]:
pip install scipy


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [22]:
pip install simpleaudio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 4.0 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for simpleaudio: filename=simpleaudio-1.0.4-cp312-cp312-macosx_10_9_universal2.whl size=2042342 sha256=014118f86dce2ffdc238f0c700dcadebd0a26aa3fceeb8c649a1894e45f6148b
  Stored in directory: /Users/jieji/Library/Caches/pip/wheels/1d/ad/93/be934a93f1ba8922256840f1cf0e59f8a21e2539985616b64f
Successfully built simpleaudio

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [27]:
# Assignment 1 - Time Scaling Function

# Part A

import scipy.io.wavfile as wav
import scipy.signal as signal
import numpy as np


# Assuming 'path_to_your_file.wav' is the path to your WAV file
file_path = 'train32.wav'

# Read the audio file
fs1, x1 = wav.read('train32.wav')

# Print the sampling rate
print("Sampling Rate:", fs1, "Hz")

# Print the shape of x1
print("Shape of x1:", x1.shape)

# If you want to determine the number of channels and length in seconds:
num_channels = x1.shape[1] if len(x1.shape) > 1 else 1
print("Number of Channels:", num_channels)

length_seconds = len(x1) / fs1
print("Length of Audio in Seconds:", length_seconds)



Sampling Rate: 32000 Hz
Shape of x1: (50313,)
Number of Channels: 1
Length of Audio in Seconds: 1.57228125


In [28]:
# Assignment 1 - Playing and Plotting Time Scaled Audio Files

# Part B
import scipy.io.wavfile as wav
import scipy.signal
import numpy as np

# Load the original WAV file
file_path = 'train32.wav'  # Replace with your file path
fs1, x1 = wav.read('train32.wav')

# Define new sampling rates
fs2 = int(fs1 / 2)  # 16 kHz
fs3 = int(1.5 * fs1) # Ensure it's an integer

# Function to resample and write to a new WAV file
def resample_and_write(original_data, original_fs, new_fs, output_filename):
    # Calculate new number of samples
    num_samples = int(len(original_data) * float(new_fs) / original_fs)

    # Resample the audio
    resampled_data = scipy.signal.resample(original_data, num_samples)

    # Ensure data type is int16 (common for WAV files)
    resampled_data = np.asarray(resampled_data, dtype=np.int16)

    # Write to a new WAV file
    wav.write(output_filename, new_fs, resampled_data)

# Resample and save the files
resample_and_write(x1, fs1, fs2, 'resampled_16kHz.wav')
resample_and_write(x1, fs1, fs3, 'resampled_1.5xfs1.wav')


In [4]:
# Part C

import simpleaudio as sa
import scipy.io.wavfile as wav

# Paths to the train sound files
original_file = 'train32.wav'
resampled_16kHz_file = 'resampled_16kHz.wav'
resampled_1_5xfs1_file = 'resampled_1.5xfs1.wav'


def play_audio(file_path):
    # Read the WAV file
    fs, audio_data = wav.read('train32.wav')

    audio_data = audio_data.astype(np.int16)

    # Determine the number of channels based on the shape of the audio data
    num_channels = 1 if len(audio_data.shape) == 1 else audio_data.shape[1]


    # Play the audio
    try:
      wave_obj = sa.WaveObject(audio_data, num_channels)
      play_obj = wave_obj.play()
      play_obj.wait_done()
    except Exception as e:
      print(f"Error playing")
      return None

# Paths to the files
original_file = 'train32.wav'
resampled_16kHz_file = 'resampled_16kHz.wav'
resampled_1_5xfs1_file = 'resampled_1.5xfs1.wav'

print("Playing train32.wav")
play_audio(original_file)

print("Playing 16kHz resampled file")
play_audio(resampled_16kHz_file)

print("Playing 1.5xfs1 resampled file")
play_audio(resampled_1_5xfs1_file)


Playing train32.wav


: 

###  Discussion
The wrong sampling frequency can significantly alter the audio's pitch, speed, and quality, resulting in a listening experience that is markedly different from what was intended by the creators of the audio content. When the incorrect sampling frequency is used to play back an audio file, several noticeable changes can occur in the audio's characteristics. The sampling frequency, or sample rate, is a crucial parameter in digital audio that determines how many samples of the audio signal are captured per second.

## Assignment 2 -- Amplitude Operations on Signals

In [2]:
# Part A
import numpy as np
import scipy.io.wavfile as wav

# Read your original audio file
file_path = 'train32.wav'  # Replace with your file path
fs1, x1 = wav.read(file_path)

# Calculate n0, the number of samples up to t=0.5 seconds
n0 = int(fs1 * 0.5)

# Create s1
s1 = np.concatenate((np.ones(n0), 0.2 * np.ones(len(x1) - n0)))

# Multiply x1 with s1 to create v1
# Adjust the shape of s1 to match x1 in case of stereo audio
if len(x1.shape) > 1:
    s1 = s1[:, np.newaxis]

v1 = x1 * s1

# Save the new signal to a wav file
output_file = 'modified_signal.wav'
wav.write(output_file, fs1, v1.astype(np.int16))  # Converting to int16 for WAV format


In [3]:
# Part B
import numpy as np
import scipy.io.wavfile as wav

# Assuming you have already read your original audio file and have fs1 and x1
# fs1, x1 = wav.read('path_to_your_audio_file.wav')

# Create r1, a decaying ramp signal
r1 = np.linspace(1, 0, len(x1))

# Multiply x1 with r1 to create v2
v2 = x1 * r1[:, np.newaxis] if x1.ndim > 1 else x1 * r1

# Save the new signal to a wav file
output_file_v2 = 'modified_signal_v2.wav'
wav.write(output_file_v2, fs1, v2.astype(np.int16))  # Converting to int16 for WAV format



In [4]:
import simpleaudio as sa

def play_audio(file_name):
  try:
    wave_obj = sa.WaveObject.from_wave_file('train32.wav')
    play_obj = wave_obj.play()
    return play_obj
  except Exception as e:
    print(f"Error playing {file_name}: {e}")
    return None

# Replace with the actual file paths of your audio files
original_file = 'train32.wav'
v1_file = 'modified_signal.wav'
v2_file = 'modified_signal_v2.wav'

# Play the original file
play_original = play_audio(original_file)
if play_original:
    play_original.wait_done()  # Wait for the original file to finish

# Play v1 file
play_v1 = play_audio(v1_file)
if play_v1:
    play_v1.wait_done()  # Wait for v1 file to finish

# Play v2 file
play_v2 = play_audio(v2_file)
if play_v2:
    play_v2.wait_done()  # Wait for v2 file to finish


: 

###  Discussion

In examining the effects of two modifications on an audio signal, the first likely alters characteristics such as amplitude or frequency within a specified time range, impacting loudness or pitch, while the second modification applies a different or more intense alteration. For instance, if the first increases amplitude, the second might decrease it or add an effect like reverb. Setting a segment of the signal, s1, to a value of 2 for the [0, 0.5] time range would amplify that part of the signal, increasing its loudness.

## Assignment 3 -- Time Scaling Audio Signals

In [1]:
# Part A
import numpy as np

def timescale(x, fs, a):

    n = len(x)
    t = np.arange(n) / fs
    t_scaled = t / a
    x_scaled = np.interp(t_scaled, t, x)
    return x_scaled, t_scaled

In [2]:
# Part B (a)
import numpy as np

# Assuming x1 (your original audio signal) and fs (the sampling rate) are already defined
# For demonstration, let's create a dummy signal and define a sampling rate
fs = 44100  # Standard sampling rate for audio (44.1 kHz)
duration = 1  # 1 second duration
t_x1 = np.linspace(0, duration, fs * duration, endpoint=False)
x1 = np.sin(2 * np.pi * 440 * t_x1)  # Example signal: 440 Hz sine wave

def timescale(x, fs, a):
    """
    Scales the time of an audio signal.

    Parameters:
    x (numpy array): Input audio signal.
    fs (int): Sampling rate of the audio signal.
    a (float): Time scaling factor.

    Returns:
    numpy array, numpy array: Scaled audio signal and corresponding time vector.
    """
    n = len(x)
    t = np.arange(n) / fs
    t_scaled = t / a
    x_scaled = np.interp(t_scaled, t, x)
    return x_scaled, t_scaled

# Create w(t) using a=2
w, t_w = timescale(x1, fs, 2)
(w, t_w)



(array([ 0.        ,  0.03132416,  0.06264832, ..., -0.09384942,
        -0.06264832, -0.03132416]),
 array([0.00000000e+00, 1.13378685e-05, 2.26757370e-05, ...,
        4.99965986e-01, 4.99977324e-01, 4.99988662e-01]))

In [3]:
# Part B (b)

# Create v(t) using a=0.5
v, t_v = timescale(x1, fs, 0.5)
(v, t_v)



(array([ 0.        ,  0.12505052,  0.24813785, ..., -0.06264832,
        -0.06264832, -0.06264832]),
 array([0.00000000e+00, 4.53514739e-05, 9.07029478e-05, ...,
        1.99986395e+00, 1.99990930e+00, 1.99995465e+00]))

In [ ]:
# Part C

In [ ]:
# Part D

###  Discussion

Suppose a student runs the figure command before every call to subplot. When you run your script, what changes do you expect to see? How will the plots change?

## Assignment 4 -- Time Shift Operations

In [ ]:
# Part A
# TODO: Code that solves A

# Part B
# TODO: Code that solves B

# Part C
# TODO: Code that solves C

### Discussion

There is a trivial case that you should ideally test for. If the shift is zero, then the output is the original signal. If the shift is an advance bigger than the original signal, then the output will be zero. Comment on whether your current implementation correctly handles these cases and whether there is a better implementation.


# Assignment 1: Working with Sound Files
### Part A